### ISSUE TITLE
CommandBuffer not triggering events

### ISSUE THREAD

**Issue by Danon5** [friflo/Friflo.Engine.ECS#10]
It seems that playing back buffered commands does not trigger reactive events. Here is a simple repro, obviously just swap the log out for whatever logging method works in your environment. Is this just a limitation of the implementation?

```cs
var store = new EntityStore();
store.OnComponentAdded += _ => {
    Debug.Log("Ran");
};
            
var normalEntity = store.CreateEntity();
normalEntity.AddComponent(new SomeComponent()); // Logs "Ran"
            
var cb = store.GetCommandBuffer();
var bufferedEntityId = cb.CreateEntity();
cb.AddComponent(bufferedEntityId, new SomeComponent());
cb.Playback(); // Does not log "Ran"
```

**Comment by friflo** [comment]
Agree, a user will expect to get entity events on component/tags add/remove.

**Comment by friflo** [comment]
published https://www.nuget.org/packages/Friflo.Engine.ECS/3.0.0-preview.13
containing the fix
