### ISSUE TITLE
Instead of using arrays directly, use a wrapped collection for StructHeap and IdArray

### ISSUE THREAD

**Issue by vkensou** [friflo/Friflo.Engine.ECS#41]
I am using Friflo in Unity, and I want to use job system with it. But Unity can only use value types (NativeArray etc.) in the job system. So I must modify a lot of code. But if Friflo uses a wrapped collection, then I only need to modify a little code. 

And this proposal depends on the Dispose proposal: https://github.com/friflo/Friflo.Engine.ECS/issues/40

**Comment by friflo** [comment]
Hm, 
Right `StructHeap` / `StructHeap<>` are reference types. They also use fields with reference types internally. E.g.
```cs
class StructHeap<T> {
    internal T[] components;
    ...
}
```
I assume these `components` is what you want inside a Unity Job.
I assume you may also want to access the `Archetype.entityIds` inside a UnityJob.
```cs
class Archetype {
    internal int[] entityIds;
    ...
}
```
Friflo ECS must not have any dependency to Unity types like NativeArray<>.
If doing this the ECS cannot be used in any other platform than Unity.

So the only way I see to use `components` and `entityIds` inside a Unity Job is to wrap them in a `NativeArray<>` when passing them to a Unity Job. E.g.
```cs
    var nativeComponents = new NativeArray(components, Allocator.None)
```

Related to this also `Chunks<>`, `QueryChunks<>` and `ChunkEnumerator<>` are using a few reference internally. So these type can also not be used inside a Unity Job.
Not sure but I assume you want these types inside a Unity Job too.

*Note:*  
In this project I cannot change these types to value types. It would mean to re implement the whole internal implementation. The effort doing this require many months. It also will degrade performance required for lookup of components of a specific type.

Can you show a code snippet how you use components inside a Unity Job?
